# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build pepijno nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["pepijno_left nice_view_adapter nice_view","pepijno_right nice_view_adapter nice_view"]'
